FROM nvidia/cuda:12.4.1-base-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PYTHONUNBUFFERED=1

# Install system dependencies and build tools
RUN apt-get update && apt-get install -y \
    git \
    wget \
    unzip \
    build-essential \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    liblzma-dev \
    tk-dev \
    uuid-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python 3.12 from source
RUN wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz && \
    tar xzf Python-3.12.0.tgz && \
    cd Python-3.12.0 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && \
    make altinstall && \
    cd .. && \
    rm -rf Python-3.12.0 Python-3.12.0.tgz

# Set python3.12 as the default Python version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.12 1 && \
    update-alternatives --config python3 --skip-auto

# Manually install distutils using a setup tool
# RUN curl -O https://files.pythonhosted.org/packages/py3/d/distutils/distutils-3.12.0.tar.gz && \
#     tar -xzvf distutils-3.12.0.tar.gz && \
#     cd distutils-3.12.0 && \
#     python3.12 setup.py install && \
#     cd .. && \
#     rm -rf distutils-3.12.0 distutils-3.12.0.tar.gz

# Upgrade pip and setuptools
RUN python3 -m ensurepip && python3 -m pip install --upgrade pip setuptools

# Clone the Git repository
ARG REPO_URL=https://github.com/OluwadareLab/EmbedTAD.git
RUN git clone $REPO_URL /workspace

# Set the working directory
WORKDIR /workspace

# Install required Python packages
RUN if [ -f "requirements.cpu.txt" ]; then python3 -m pip install -r requirements.cpu.txt; fi

# Set the home directory
ENV HOME=/workspace

# Default command
CMD ["/bin/bash"]