name: embedtad
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - cupy=13.3
  - cugraph=23.10
  - scipy=1.15.1
  - scikit-learn=1.6.1
  - tqdm=4.65.0
  - seaborn=0.13.2
  - cudatoolkit=12.4
